### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by m00nk** [lan143/yii2-yandexturbo#1]
Действительно ли пакету нужен PHP 7.1 ? 

На 7.0 не заведется? Если 7.0 достаточно для работы, то не могли бы Вы понизить требуемую версию до 7.0?

Спасибо.

**Comment by lan143** [comment]
В коде используются вещи, которые были добавлены в версии 7.1 Просто понизить версию не получится, нужно ещё слегка модифицировать код.

**Comment by m00nk** [comment]
Да, я уже сделал в форке.

---
С уважением,
Дмитрий Шереметьев


пт, 19 июл. 2019 г. в 15:53, Kravchenko Artyom <notifications@github.com>:
